steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mylearningproject/nodejs-gcp-build:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mylearningproject/nodejs-gcp-build:$SHORT_SHA']  
