steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mylearningproject-320411/nodejs-gcp-build:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mylearningproject-320411/nodejs-gcp-build:$SHORT_SHA'] 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-first-run', '--region=us-central1', '--platform=managed', '--image=gcr.io/mylearningproject-320411/nodejs-gcp-build@sha256:992091391ecdcb1a63243722e4e57cf2dbd132e9e22d08786375996b85715a7c'] 
